### ISSUE TITLE
Console：Uncaught Unhandled exception: The null object does not have a method 'nextInt'...(anonymous function).md	

### ISSUE THREAD

**Issue by wendy515** [DEIT2014/assignment#13]
```
import 'dart:html';
import 'dart:math';

void main() {
  querySelector('#sample_text_id')
     // ..text='点我'
      ..onClick.listen(generate);

}
void generate(MouseEvent e) {
 //找随机数
var randomVar;//新建一个可变的随机数
var num=randomVar.nextInt(3);//人数
var student=new Map();
Map<int,String>name = {'0': '杜谦',
  '1': '李志伟',
  '2': '吴怡雯'};
if(num==0)
  querySelector('#sample').text=name['0'];
if(num==1)
  querySelector('#sample').text=name['1'];
if(num==2)
  querySelector('#sample').text=name['2'];
//for (var book in student.keys) {
  //print('$book was written by ${student[book]}');
//}
}
```

当断点放在“var student=new Map();”这行时，console框出现红字

```
Uncaught Unhandled exception:
The null object does not have a method 'nextInt'.

NoSuchMethodError: method not found: 'nextInt'
Receiver: null
Arguments: [3]
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:44)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      generate (http://localhost:63342/random/web/random.dart:13:19)
  (anonymous function)  
```

哪里有问题？

**Comment by wendy515** [comment]
首先判断出应该是

``` dart
var num=randomVar.nextInt(3);
```

这行出了问题。
报错：

> The null object does not have a method 'nextInt'.
> 意思是randomVar这个对象不存在，说明没有定义randomVar，虽然写了"var randomVar;"但是没有指明这个对象的类或数据类型，因此定义不完整，应该改成  

``` dart
var randomVar=new Random();
```

然后就可以运行了。

**Comment by meflyup** [comment]
非常好！我顺便把你的格式修订了
